# -*- coding: utf-8 -*-
"""Atividade2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15x04sLCcqNM3DGvP-ZwaDlrBr2v4scQj
"""

raio = float(input("Digite o raio do circulo: "))

area = 3.14*(raio)**2

print(f"A area do circulo eh: {area:.2f}")