# -*- coding: utf-8 -*-
"""Atividade3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hFpB011IteLZA0iFdNXIWGm-PWpbOYvd
"""

idade = int(input("Digite sua idade: "))

if (idade >= 18):
    print("\nVocê é maior de idade.")
else:
    print("\nVocê é menor de idade.")