# -*- coding: utf-8 -*-
"""Atividade1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rAudfbYGo15UPnZy7vHp_S4k8nkX8vmN
"""

num1 = float(input("Digite um numero: "))
num2 = float(input("Digite o segundo numero: "))

soma = num1 + num2
sub = num1 - num2
mult = num1*num2
div = num1/num2

print("\nA soma eh: ", soma)
print("A subtracao eh: ", sub)
print("A multiplicacao eh: ", mult)
print(f"A divisão é: {div:.2f}")