# -*- coding: utf-8 -*-
"""Gráfico Boxplot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xgRWd86d65F15GZ3l5-UIEkpPm5sbfoZ

# Prática de aula - Vizualização de dados

## Vizualização 3
"""

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd

# Leitura dos dados
df = sns.load_dataset('tips')

df.head()

# Criação de gráfico
ax = sns.boxplot(x='day', y='total_bill', data=df)

# Ajustando o gráfico
sns.set_style("whitegrid")

plt.figure(figsize=(7,5))
ax = sns.boxplot(x='day', y='total_bill', data=df, color='yellow')

plt.xlabel('Dias da semana')
plt.ylabel('Total de gorjetas (USD)')
plt.title('Distribuição de gorjetas ao longo da semana')
plt.show()