# -*- coding: utf-8 -*-
"""Gráfico de Histograma.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DwMf9djKIiblM8ZnyTQ5s6DBLWA5dJib

# Prática de aula - Vizualização de dados

## Vizualização 2
"""

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd

df = sns.load_dataset('penguins')

df.head()

# Criando o gráfico de histograma
ax = sns.histplot(data=df, x='body_mass_g')

#Ajustando o gráfico
sx = sns.histplot(data=df, x='body_mass_g',color='orange')
sns.set_style("whitegrid")
plt.ylabel('Quantidade de pinguins')
plt.xlabel("Massa (g)")
plt.title("Distribuição de massa dos pinguins")

ax.set(frame_on=False)
ax.axhline(0, color="k", clip_on=False)
plt.show()