# -*- coding: utf-8 -*-
"""Gráfico de Barras.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l00mmd0gCwPi08wMq7ffdU6oANVFOADl

# Prática de aula - Vizualização de dados

## Vizualização 1
"""

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd

# leitura dos dados
df = pd.read_csv('https://gist.githubusercontent.com/omadson/770934cb0df9e2d2c3e8db031f1139a5/raw/4d181efc035b327d9d66256915951384517c603e/arrecadacao.csv')

df.head()

# Criando um gráfico de barras
arrecadacao_milhao = df['arrecadacao'] / 1000000  # Dividindo por 1 milhão para facilitar a leitura
df['arrecadacao_milhao'] = arrecadacao_milhao  # Adicionando a coluna 'arrecadacao_milhao' ao DataFrame
df = df.sort_values(by='arrecadacao_milhao', ascending=True)

plt.figure(figsize=(10, 6))
plt.barh(df['titulo'], df['arrecadacao_milhao'])
plt.xlabel('Arrecadação (em milhões)')
plt.ylabel('Título')
plt.title('Arrecadação por Título')

# Adicionando rótulos de valores nas barras
for i, valor in enumerate(df['arrecadacao_milhao']):
    plt.text(valor, i, f'{valor:.2f} Mi', va='center')

plt.show()